baseURL = 'https://www.kerngesund.com/'
languageCode = 'de-DE'
title = 'Inspiration des Tages'
theme = 'ananke'
DefaultContentLanguage = 'de'
SectionPagesMenu = 'main'
enableRobotsTXT = true
[params]
  favicon = 'favicon.ico'
  site_logo = 'favicon.ico'
