baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Quotes'
    pageRef = '/quotes'
    weight = 20

  [[menus.main]]
    name = 'Categories'
    pageRef = '/categories'
    weight = 30

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
