name: Makefile CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Build
      
      - name: Install dependencies
        run: |
          sudo apt install -y python3-pip
          pip install percy-selenium
      
      - name: Node clean install
        run: cd inspiration-app && npm ci
      
      - name: Use dev quotes
        run: cd inspiration-app/src/assets/ && rm -f quotes.js && ln -s quotes.js.dev quotes.js
      
      - name: Run build
        run: cd inspiration-app && npm run build
      
      - name: Run webserver
        run: cd inspiration-app && npm run dev &
      
      - name: Run Test
        run: cd inspiration-app/ && node_modules/.bin/percy exec -- python3 tests/inspiration-app.py || true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          MOZ_HEADLESS: 1
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: logfile
          path: ./**/*.log
